### ISSUE TITLE
error running `migrate --reset`

### ISSUE THREAD

**Issue by px3l** [strange-labs-uk/ethereum-raffle#32]
Am I using the wrong network? is there a specific network we need?

```
Compiling ./contracts/HashKeyRaffle.sol...
Compiling ./contracts/Ownable.sol...
Compiling zeppelin-solidity/contracts/math/SafeMath.sol...
Writing artifacts to ./build/contracts

Using network 'develop'.

Error: Attempting to run transaction which calls a contract function, but recipient address 0x8cdaf0cd259887258bc13a92c0a6da92698644c0 is not a contract address
    at Object.InvalidResponse (/home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/px3l/.nvm/versions/node/v7.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by brtknr** [comment]
Try this:

First update all the packages to the latest. Run the following inside `truffle` folder:

```
npm install
npm install -g truffle
nom install -g ganache-cli
```

Then run `ganache-cli` on a separate window:

```
ganache-cli -b 3
```

Then,
```
truffle compile
truffle migrate --reset --network ganache
```

**Comment by px3l** [comment]
thanks that worked
